using CannoliKit.Interfaces;
using CannoliKit.Modules.Routing;
using Discord.WebSocket;

namespace CannoliKit.Modules
{
    /// <summary>
    /// Configuration generated by a <see cref="ICannoliModuleFactory"/>, for use by a <see cref="CannoliModule{TContext,TState}"/>.
    /// </summary>
    public class CannoliModuleFactoryConfiguration
    {
        internal CannoliModuleFactoryConfiguration(
            SocketUser requestingUser,
            RouteConfiguration? routing = null)
        {
            RequestingUser = requestingUser;
            Routing = routing;
        }

        /// <summary>
        /// The user that initiated the interaction in the current context.
        /// </summary>
        public SocketUser RequestingUser { get; init; }

        /// <summary>
        /// Custom Cannoli Route configuration.
        /// </summary>
        public RouteConfiguration? Routing { get; init; }
    }
}
