using CannoliKit.Interfaces;

namespace CannoliKit.Modules.Routing
{
    /// <summary>
    /// Cannoli Route configuration generated by <see cref="RouteConfigurationBuilder"/> for use with a <see cref="ICannoliModuleFactory"/>.
    /// </summary>
    public sealed class RouteConfiguration
    {
        internal RouteConfiguration(
            IReadOnlyDictionary<string, CannoliRouteId> returnRouteIds,
            CannoliRouteId? cancellationRouteId = null)
        {
            ReturnRouteIds = returnRouteIds;
            CancellationRouteId = cancellationRouteId;
        }

        internal RouteConfiguration()
        {
            ReturnRouteIds = new Dictionary<string, CannoliRouteId>();
        }

        internal CannoliRouteId? CancellationRouteId { get; }
        internal IReadOnlyDictionary<string, CannoliRouteId> ReturnRouteIds { get; }
    }
}
